# Generated by Django 2.1.7 on 2019-05-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmessage',
            name='client',
            field=models.CharField(max_length=30),
        ),
    ]
